name: Build and push Bento Keycloak distribution

on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download gosu
        run: |
          cd build
          wget https://github.com/tianon/gosu/releases/download/1.16/gosu-amd64
          wget https://github.com/tianon/gosu/releases/download/1.16/gosu-arm64
          cd ..
          ls -l && ls -l build/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/bento-platform/bento_keycloak_dist
          tags: |
            type=raw,value=latest
            type=raw,value={{date 'YYYY.MM.DD'}}
            type=raw,value={{date 'YYYY.MM.DD.HH'}}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
